# this is my first docker compose file

version: '3'
services:

nginx:
  image: nginx
  volumes:
    - ./templates:/etc/nginx/templates
  ports:
    - "8080:8080"
  enviroment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=8080